apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisecow-tls
spec:
  secretName: wisecow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - wisecow.example.com  